import ACUIHE.Solver.Search.FiniteLanguageSystem.Construction

/-!
Operational and algebraic output-language semantics for variable-labelled trees.
-/

namespace ACUIHE.Solver.Search

open ACUIHE.Solver.Linear

universe u

attribute [local instance]
  finiteLanguageDecidableEq finiteLanguageBoolFinEnum

/-- All mirrored output words generated by a labelled candidate tree from a
pending state.  Active words are recorded at the current node; recursively
propagating them also records precisely the variable seeds introduced below
that node. -/
def generatedOutputs
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (row : Row) (side : Bool) : Tree Hom (VariableLabel Variable) →
      Finset (List Hom)
  | .leaf label =>
      (activePendingWords problem state label row side).image Subtype.val
  | .node label children =>
      (activePendingWords problem state label row side).image Subtype.val ∪
        Finset.univ.biUnion fun branch =>
          (generatedOutputs problem
            ((finiteLanguageAutomaton problem).next state label branch)
            row side (children branch)).image (List.cons branch)

@[simp]
theorem nil_mem_generatedOutputs_iff
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool) :
    [] ∈ generatedOutputs problem state row side tree ↔
      hasEndpoint
        (activePendingWords problem state tree.root row side) = true := by
  cases tree <;> simp [generatedOutputs, hasEndpoint_eq_true_iff, Tree.root]

theorem active_value_mem_generatedOutputs
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool)
    (word : PendingWord problem)
    (membership : word ∈ activePendingWords problem state
      tree.root row side) :
    word.1 ∈ generatedOutputs problem state row side tree := by
  cases tree with
  | leaf label =>
      exact Finset.mem_image.mpr ⟨word, membership, rfl⟩
  | node label children =>
      apply Finset.mem_union_left
      exact Finset.mem_image.mpr ⟨word, membership, rfl⟩

@[simp]
theorem cons_mem_generatedOutputs_node_iff
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (label : VariableLabel Variable)
    (children : Hom → Tree Hom (VariableLabel Variable))
    (row : Row) (side : Bool) (branch : Hom) (word : List Hom) :
    branch :: word ∈
        generatedOutputs problem state row side (.node label children) ↔
      word ∈ generatedOutputs problem
        ((finiteLanguageAutomaton problem).next state label branch)
        row side (children branch) := by
  simp [generatedOutputs, finiteLanguageAutomaton, activePendingWords]
  intro bounded membership
  let suffix : PendingWord problem :=
    ⟨word, (mem_wordsUpTo_iff _ _).mpr
      (le_trans (Nat.le_succ word.length) bounded)⟩
  apply active_value_mem_generatedOutputs problem _ _ row side suffix
  apply Finset.mem_union_left
  apply (mem_consumePendingWords_iff branch _ suffix).mpr
  exact ⟨⟨branch :: word, (mem_wordsUpTo_iff _ _).mpr bounded⟩,
    Finset.mem_union.mpr membership, rfl⟩

/-- Local endpoint checks plus exact propagation imply inclusion of all
mirrored words generated by an accepted candidate tree. -/
theorem finiteLanguageAutomaton_accepts_generated_subset
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable))
    (accepted : (finiteLanguageAutomaton problem).Accepts state tree)
    (row : Row) :
    generatedOutputs problem state row false tree ⊆
      generatedOutputs problem state row true tree := by
  induction accepted with
  | @leaf state label valid terminal =>
      intro word membership
      have validRule : ∀ row,
          hasEndpoint
              (activePendingWords problem state label row false) = true →
            hasEndpoint
              (activePendingWords problem state label row true) = true := by
        simpa [finiteLanguageAutomaton] using valid
      have terminalRule : ∀ row side pending,
          pending ∈ activePendingWords problem state label row side →
            pending.1 = [] := by
        simpa [finiteLanguageAutomaton] using terminal
      rcases Finset.mem_image.mp membership with
        ⟨pending, pendingMembership, wordEquality⟩
      have wordEmpty : word = [] := by
        rw [← wordEquality]
        exact terminalRule row false pending pendingMembership
      subst word
      have rightEmpty : [] ∈ generatedOutputs problem state row true
          (.leaf label) := by
        apply (nil_mem_generatedOutputs_iff problem state
          (.leaf label) row true).mpr
        apply validRule row
        apply (nil_mem_generatedOutputs_iff problem state
          (.leaf label) row false).mp
        simpa [terminalRule row false pending pendingMembership] using membership
      simpa [terminalRule row false pending pendingMembership] using rightEmpty
  | @node state label children valid descendants inductionHypothesis =>
      intro word membership
      cases word with
      | nil =>
          apply (nil_mem_generatedOutputs_iff problem state
            (.node label children) row true).mpr
          have validRule : ∀ row,
              hasEndpoint
                  (activePendingWords problem state label row false) = true →
                hasEndpoint
                  (activePendingWords problem state label row true) = true := by
            simpa [finiteLanguageAutomaton] using valid
          apply validRule row
          exact (nil_mem_generatedOutputs_iff problem state
            (.node label children) row false).mp membership
      | cons branch word =>
          apply (cons_mem_generatedOutputs_node_iff problem state
            label children row true branch word).mpr
          apply inductionHypothesis branch
          exact (cons_mem_generatedOutputs_node_iff problem state
            label children row false branch word).mp membership

/-- Direct description of the mirrored language generated by a state and a
labelled candidate tree. -/
def evaluatedOutputs
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool) :
    Finset (List Hom) :=
  (state row side).image Subtype.val ∪
    Finset.univ.biUnion fun index =>
      Finset.image₂ (fun assignmentPath coefficient =>
          assignmentPath ++ coefficient.1)
        (tree.language (fun label => decide (index ∈ label)))
        (variableCoefficientWords problem side row index)

theorem generatedOutputs_leaf_eq_evaluated
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (label : VariableLabel Variable) (row : Row) (side : Bool) :
    generatedOutputs problem state row side (.leaf label) =
      evaluatedOutputs problem state (.leaf label) row side := by
  ext word
  simp [generatedOutputs, evaluatedOutputs, activePendingWords,
    coefficientSeeds, Tree.language]
  aesop

@[simp]
theorem nil_mem_evaluatedOutputs_iff
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool) :
    [] ∈ evaluatedOutputs problem state tree row side ↔
      hasEndpoint
        (activePendingWords problem state tree.root row side) = true := by
  cases tree <;>
    simp [evaluatedOutputs, activePendingWords, coefficientSeeds,
      Tree.language, Tree.root, hasEndpoint_eq_true_iff] <;>
    aesop

theorem mem_evaluatedOutputs_iff
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool)
    (word : List Hom) :
    word ∈ evaluatedOutputs problem state tree row side ↔
      (∃ pending, pending ∈ state row side ∧ pending.1 = word) ∨
      ∃ index assignmentPath coefficient,
        assignmentPath ∈ tree.language
          (fun label => decide (index ∈ label)) ∧
        coefficient ∈ variableCoefficientWords problem side row index ∧
        assignmentPath ++ coefficient.1 = word := by
  simp [evaluatedOutputs]

@[simp]
theorem cons_mem_evaluatedOutputs_node_iff
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (label : VariableLabel Variable)
    (children : Hom → Tree Hom (VariableLabel Variable))
    (row : Row) (side : Bool) (branch : Hom) (word : List Hom) :
    branch :: word ∈
        evaluatedOutputs problem state (.node label children) row side ↔
      word ∈ evaluatedOutputs problem
        ((finiteLanguageAutomaton problem).next state label branch)
        (children branch) row side := by
  rw [mem_evaluatedOutputs_iff, mem_evaluatedOutputs_iff]
  constructor
  · rintro (⟨pending, pendingMembership, pendingValue⟩ |
        ⟨index, assignmentPath, coefficient, assignmentMembership,
          coefficientMembership, generatedValue⟩)
    · have suffixBound : word ∈ wordsUpTo problem.pathBound := by
        apply (mem_wordsUpTo_iff _ _).mpr
        have pendingBound := (mem_wordsUpTo_iff _ pending.1).mp pending.2
        rw [pendingValue] at pendingBound
        exact le_trans (Nat.le_succ word.length) pendingBound
      let suffix : PendingWord problem := ⟨word, suffixBound⟩
      apply Or.inl
      refine ⟨suffix, ?_, rfl⟩
      change suffix ∈ consumePendingWords branch
        (activePendingWords problem state label row side)
      apply (mem_consumePendingWords_iff branch _ suffix).mpr
      exact ⟨pending, Finset.mem_union_left _ pendingMembership, pendingValue⟩
    · cases assignmentPath with
      | nil =>
          have selected : index ∈ label := by
            have checked := (Tree.nil_mem_language_iff
              (fun selectedLabel => decide (index ∈ selectedLabel))
              (.node label children)).mp assignmentMembership
            exact of_decide_eq_true checked
          have coefficientValue : coefficient.1 = branch :: word := by
            simpa using generatedValue
          have suffixBound : word ∈ wordsUpTo problem.pathBound := by
            apply (mem_wordsUpTo_iff _ _).mpr
            have coefficientBound := (mem_wordsUpTo_iff _ coefficient.1).mp coefficient.2
            rw [coefficientValue] at coefficientBound
            exact le_trans (Nat.le_succ word.length) coefficientBound
          let suffix : PendingWord problem := ⟨word, suffixBound⟩
          apply Or.inl
          refine ⟨suffix, ?_, rfl⟩
          change suffix ∈ consumePendingWords branch
            (activePendingWords problem state label row side)
          apply (mem_consumePendingWords_iff branch _ suffix).mpr
          refine ⟨coefficient, Finset.mem_union_right _ ?_, coefficientValue⟩
          exact Finset.mem_biUnion.mpr
            ⟨index, selected, coefficientMembership⟩
      | cons first rest =>
          have restMembership : rest ∈
              (children first).language
                (fun selectedLabel => decide (index ∈ selectedLabel)) :=
            (Tree.cons_mem_language_node_iff _ _ _ _ _).mp assignmentMembership
          have generatedParts : first = branch ∧
              rest ++ coefficient.1 = word :=
            List.cons.inj (by simpa using generatedValue)
          have headEquality : first = branch := generatedParts.1
          have tailEquality : rest ++ coefficient.1 = word := generatedParts.2
          subst first
          apply Or.inr
          exact ⟨index, rest, coefficient, restMembership,
            coefficientMembership, tailEquality⟩
  · rintro (⟨suffix, suffixMembership, suffixValue⟩ |
        ⟨index, assignmentPath, coefficient, assignmentMembership,
          coefficientMembership, generatedValue⟩)
    · change suffix ∈ consumePendingWords branch
          (activePendingWords problem state label row side) at suffixMembership
      rcases (mem_consumePendingWords_iff branch _ suffix).mp suffixMembership with
        ⟨pending, pendingMembership, pendingValue⟩
      rcases Finset.mem_union.mp pendingMembership with stateMembership | seedMembership
      · exact Or.inl ⟨pending, stateMembership, by
          rw [pendingValue, suffixValue]⟩
      · rcases Finset.mem_biUnion.mp seedMembership with
          ⟨index, selected, coefficientMembership⟩
        apply Or.inr
        refine ⟨index, [], pending, ?_, coefficientMembership, ?_⟩
        · exact (Tree.nil_mem_language_iff
            (fun selectedLabel => decide (index ∈ selectedLabel))
            (.node label children)).mpr (by
              change decide (index ∈ label) = true
              exact decide_eq_true selected)
        · rw [List.nil_append, pendingValue, suffixValue]
    · apply Or.inr
      refine ⟨index, branch :: assignmentPath, coefficient, ?_,
        coefficientMembership, ?_⟩
      · exact (Tree.cons_mem_language_node_iff _ _ _ _ _).mpr
          assignmentMembership
      · simp [generatedValue]

/-- Operational suffix propagation is extensionally equal to the direct
language description. -/
theorem generatedOutputs_eq_evaluatedOutputs
    {Row Variable Hom : Type u}
    [FinEnum Row] [FinEnum Variable] [FinEnum Hom] [Encodable Hom]
    (problem : FiniteLanguageSystem Row Variable Hom) (state : PendingState problem)
    (tree : Tree Hom (VariableLabel Variable)) (row : Row) (side : Bool) :
    generatedOutputs problem state row side tree =
      evaluatedOutputs problem state tree row side := by
  induction tree generalizing state with
  | leaf label =>
      exact generatedOutputs_leaf_eq_evaluated
        (Row := Row) (Variable := Variable) (Hom := Hom)
        problem state label row side
  | node label children inductionHypothesis =>
      ext word
      cases word with
      | nil =>
          rw [nil_mem_generatedOutputs_iff, nil_mem_evaluatedOutputs_iff]
      | cons branch word =>
          rw [cons_mem_generatedOutputs_node_iff,
            cons_mem_evaluatedOutputs_node_iff,
            inductionHypothesis branch]




end ACUIHE.Solver.Search
