import ACUIhE.Equation.Definition

/-!
# Equational derivability in ACUIh

The rules here concern only the ACUIh fragment. The quotient term model
connects derivability to validity in all ACUIh algebras.
-/

namespace ACUIhE.ACUIh

universe u v w x

/-- Equational derivations using precisely the ACUI and homomorphism laws. -/
inductive Derives {Const : Type u} {Var : Type v} {Hom : Type w} :
    Term Const Var Hom → Term Const Var Hom → Prop where
  | refl (term : Term Const Var Hom) : Derives term term
  | symm {left right : Term Const Var Hom} :
      Derives left right → Derives right left
  | trans {left middle right : Term Const Var Hom} :
      Derives left middle → Derives middle right → Derives left right
  | add_congr {left₁ left₂ right₁ right₂ : Term Const Var Hom} :
      Derives left₁ right₁ → Derives left₂ right₂ →
        Derives (.add left₁ left₂) (.add right₁ right₂)
  | hom_congr (name : Hom) {left right : Term Const Var Hom} :
      Derives left right → Derives (.hom name left) (.hom name right)
  | add_assoc (a b c : Term Const Var Hom) :
      Derives (.add (.add a b) c) (.add a (.add b c))
  | add_comm (a b : Term Const Var Hom) : Derives (.add a b) (.add b a)
  | add_zero (a : Term Const Var Hom) : Derives (.add a .zero) a
  | add_idem (a : Term Const Var Hom) : Derives (.add a a) a
  | hom_add (name : Hom) (a b : Term Const Var Hom) :
      Derives (.hom name (.add a b)) (.add (.hom name a) (.hom name b))
  | hom_zero (name : Hom) :
      Derives (.hom name (.zero : Term Const Var Hom)) .zero

/-- Every ACUIh derivation preserves evaluation, in any carrier universe. -/
theorem Derives.sound {Const : Type u} {Var : Type v} {Hom : Type w}
    {α : Type x} [ACUIh Hom α]
    (interpretConst : Const → α) (interpretVar : Var → α)
    {left right : Term Const Var Hom} (derivation : Derives left right) :
    left.eval interpretConst interpretVar = right.eval interpretConst interpretVar := by
  induction derivation with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | add_congr _ _ ih₁ ih₂ =>
      simp only [Term.eval]
      rw [ih₁, ih₂]
  | hom_congr name _ ih => exact congrArg (H name) ih
  | add_assoc => exact ACUIh.add_assoc _ _ _
  | add_comm => exact ACUIh.add_comm _ _
  | add_zero => exact ACUIh.add_zero _
  | add_idem => exact ACUIh.add_idem _
  | hom_add => exact ACUIh.hom_add _ _ _
  | hom_zero => exact ACUIh.hom_zero _

theorem Derives.semanticallyEquivalent {Const : Type u} {Var : Type v} {Hom : Type w}
    {left right : Term Const Var Hom} (derivation : Derives left right) :
    SemanticallyEquivalent left right := by
  intro α _ interpretConst interpretVar
  exact derivation.sound interpretConst interpretVar

/-- The equivalence relation generated by ACUIh derivations. -/
def derivationSetoid (Const : Type u) (Var : Type v) (Hom : Type w) :
    Setoid (Term Const Var Hom) where
  r := Derives
  iseqv := ⟨Derives.refl, Derives.symm, Derives.trans⟩

/-- The fragment's term model, without any additional operators or laws. -/
def TermModel (Const : Type u) (Var : Type v) (Hom : Type w) :=
  Quotient (derivationSetoid Const Var Hom)

namespace TermModel

def ofTerm {Const : Type u} {Var : Type v} {Hom : Type w}
    (term : Term Const Var Hom) : TermModel Const Var Hom :=
  Quotient.mk (derivationSetoid Const Var Hom) term

instance {Const : Type u} {Var : Type v} {Hom : Type w} :
    Zero (TermModel Const Var Hom) where
  zero := ofTerm .zero

instance {Const : Type u} {Var : Type v} {Hom : Type w} :
    Add (TermModel Const Var Hom) where
  add := Quotient.lift₂ (fun left right => ofTerm (.add left right)) (by
    intro left₁ left₂ right₁ right₂ h₁ h₂
    exact Quotient.sound (Derives.add_congr h₁ h₂))

def hom {Const : Type u} {Var : Type v} {Hom : Type w} (name : Hom) :
    TermModel Const Var Hom → TermModel Const Var Hom :=
  Quotient.lift (fun term => ofTerm (.hom name term)) (by
    intro left right equality
    exact Quotient.sound (Derives.hom_congr name equality))

instance {Const : Type u} {Var : Type v} {Hom : Type w} :
    ACUIh Hom (TermModel Const Var Hom) where
  hom := hom
  add_assoc := by
    intro a b c
    refine Quotient.inductionOn₃ a b c ?_
    intro a b c
    exact Quotient.sound (Derives.add_assoc a b c)
  add_comm := by
    intro a b
    refine Quotient.inductionOn₂ a b ?_
    intro a b
    exact Quotient.sound (Derives.add_comm a b)
  add_zero := by
    intro a
    refine Quotient.inductionOn a ?_
    intro a
    exact Quotient.sound (Derives.add_zero a)
  add_idem := by
    intro a
    refine Quotient.inductionOn a ?_
    intro a
    exact Quotient.sound (Derives.add_idem a)
  hom_add := by
    intro name a b
    refine Quotient.inductionOn₂ a b ?_
    intro a b
    exact Quotient.sound (Derives.hom_add name a b)
  hom_zero := fun name => Quotient.sound (Derives.hom_zero name)

/-- Evaluation under the generator interpretation is the quotient map. -/
theorem eval_eq_ofTerm {Const : Type u} {Var : Type v} {Hom : Type w}
    (term : Term Const Var Hom) :
    term.eval (fun name => ofTerm (.const name)) (fun name => ofTerm (.var name)) =
      ofTerm term := by
  induction term with
  | zero => rfl
  | const => rfl
  | var => rfl
  | add _ _ ih₁ ih₂ =>
      simp only [Term.eval]
      rw [ih₁, ih₂]
      rfl
  | hom _ _ ih =>
      simp only [Term.eval]
      rw [ih]
      rfl

end TermModel

/-- Every universally valid ACUIh equation follows from the fragment's rules. -/
theorem completeness {Const : Type u} {Var : Type v} {Hom : Type w}
    {left right : Term Const Var Hom} (validity : SemanticallyEquivalent left right) :
    Derives left right := by
  have equality := validity (α := TermModel Const Var Hom)
    (fun name => TermModel.ofTerm (.const name))
    (fun name => TermModel.ofTerm (.var name))
  rw [TermModel.eval_eq_ofTerm, TermModel.eval_eq_ofTerm] at equality
  exact Quotient.exact equality

theorem soundness_and_completeness {Const : Type u} {Var : Type v} {Hom : Type w}
    {left right : Term Const Var Hom} :
    Derives left right ↔ SemanticallyEquivalent left right :=
  ⟨Derives.semanticallyEquivalent, completeness⟩

end ACUIhE.ACUIh
