(test
 (name test_solver)
 (modules test_solver)
 (libraries hypergraph))

(test
 (name test_types)
 (modules test_types)
 (libraries hypergraph))

(test
 (name test_parser)
 (modules test_parser)
 (libraries hypergraph zarith))

(test
 (name test_check)
 (modules test_check)
 (libraries hypergraph))

(test
 (name test_infer)
 (modules test_infer)
 (libraries hypergraph))

(test
 (name test_value)
 (modules test_value)
 (libraries hypergraph))
