import Mathlib.Algebra.Order.Kleene
import Mathlib.Data.Finset.NAry
import Mathlib.Logic.Encodable.Basic

/-! Finite linear contexts generated by named homomorphisms. -/

namespace ACUIHE.Solver.Linear

universe u

local instance encodableDecidableEq {α : Type*} [Encodable α] :
    DecidableEq α :=
  Encodable.decidableEqOfEncodable α

/--
A finite collection of homomorphism paths.  A path `[h₁, ..., hₙ]`
represents the linear context `h₁ (... (hₙ ·) ...)`.

Addition is union and multiplication concatenates paths.  Thus these
contexts form the finite-language semiring over the alphabet `Hom`.
-/
structure HomContext (Hom : Type u) where
  paths : Finset (List Hom)

namespace HomContext

variable {Hom : Type u}

@[ext]
theorem ext {left right : HomContext Hom}
    (equality : left.paths = right.paths) : left = right := by
  cases left
  cases right
  simp_all

instance [Encodable Hom] : DecidableEq (HomContext Hom) :=
  fun left right =>
    if equality : left.paths = right.paths then
      isTrue (ext equality)
    else
      isFalse fun contextsEqual => equality (congrArg HomContext.paths contextsEqual)

/-- The context containing no paths. -/
def empty : HomContext Hom :=
  ⟨∅⟩

/-- The context containing one homomorphism path. -/
def singleton [Encodable Hom] (path : List Hom) : HomContext Hom :=
  ⟨{path}⟩

/-- Union of two finite contexts. -/
def add [Encodable Hom] (left right : HomContext Hom) : HomContext Hom :=
  ⟨left.paths ∪ right.paths⟩

/--
Composition of finite contexts.  Paths are written outermost first, so a
path from the left context is concatenated before a path from the right.
-/
def mul [Encodable Hom] (left right : HomContext Hom) : HomContext Hom :=
  ⟨Finset.image₂ (fun leftPath rightPath => leftPath ++ rightPath)
    left.paths right.paths⟩

/-- The identity context, containing just the empty path. -/
def one [Encodable Hom] : HomContext Hom :=
  singleton []

instance : EmptyCollection (HomContext Hom) :=
  ⟨empty⟩

instance [Encodable Hom] : Singleton (List Hom) (HomContext Hom) :=
  ⟨singleton⟩

instance : Zero (HomContext Hom) :=
  ⟨empty⟩

instance [Encodable Hom] : One (HomContext Hom) :=
  ⟨one⟩

instance [Encodable Hom] : Add (HomContext Hom) :=
  ⟨add⟩

instance [Encodable Hom] : Mul (HomContext Hom) :=
  ⟨mul⟩

@[simp]
theorem paths_empty : (empty : HomContext Hom).paths = ∅ :=
  rfl

@[simp]
theorem paths_zero : (0 : HomContext Hom).paths = ∅ :=
  rfl

@[simp]
theorem paths_singleton [Encodable Hom] (path : List Hom) :
    (singleton path).paths = {path} :=
  rfl

@[simp]
theorem paths_one [Encodable Hom] : (1 : HomContext Hom).paths = {[]} :=
  rfl

@[simp]
theorem paths_add [Encodable Hom] (left right : HomContext Hom) :
    (left + right).paths = left.paths ∪ right.paths :=
  rfl

@[simp]
theorem paths_mul [Encodable Hom] (left right : HomContext Hom) :
    (left * right).paths =
      Finset.image₂ (fun leftPath rightPath => leftPath ++ rightPath)
        left.paths right.paths :=
  rfl

@[simp]
theorem mem_zero [Encodable Hom] (path : List Hom) :
    path ∉ (0 : HomContext Hom).paths := by
  simp

@[simp]
theorem mem_one [Encodable Hom] (path : List Hom) :
    path ∈ (1 : HomContext Hom).paths ↔ path = [] := by
  simp

@[simp]
theorem mem_add [Encodable Hom] (path : List Hom)
    (left right : HomContext Hom) :
    path ∈ (left + right).paths ↔ path ∈ left.paths ∨ path ∈ right.paths := by
  simp

@[simp]
theorem mem_mul [Encodable Hom] (path : List Hom)
    (left right : HomContext Hom) :
    path ∈ (left * right).paths ↔
      ∃ leftPath ∈ left.paths, ∃ rightPath ∈ right.paths,
        leftPath ++ rightPath = path := by
  simp

/-- Finite homomorphism contexts form a semiring under union and composition. -/
instance [Encodable Hom] : Semiring (HomContext Hom) where
  add_assoc left middle right := by
    apply ext
    exact Finset.union_assoc left.paths middle.paths right.paths
  zero_add context := by
    apply ext
    exact Finset.empty_union context.paths
  add_zero context := by
    apply ext
    exact Finset.union_empty context.paths
  add_comm left right := by
    apply ext
    exact Finset.union_comm left.paths right.paths
  mul_assoc left middle right := by
    apply ext
    exact Finset.image₂_assoc fun leftPath middlePath rightPath =>
      List.append_assoc leftPath middlePath rightPath
  zero_mul context := by
    apply ext
    exact Finset.image₂_empty_left
  mul_zero context := by
    apply ext
    exact Finset.image₂_empty_right
  one_mul context := by
    apply ext
    exact Finset.image₂_left_identity List.nil_append context.paths
  mul_one context := by
    apply ext
    exact Finset.image₂_right_identity List.append_nil context.paths
  natCast number := if number = 0 then 0 else 1
  natCast_zero := rfl
  natCast_succ number := by
    cases number with
    | zero =>
        apply ext
        simp
    | succ number =>
        apply ext
        simp
  left_distrib left right₁ right₂ := by
    apply ext
    exact Finset.image₂_union_right
  right_distrib left₁ left₂ right := by
    apply ext
    exact Finset.image₂_union_left
  nsmul := nsmulRec

@[simp]
theorem add_self [Encodable Hom] (context : HomContext Hom) :
    context + context = context := by
  apply ext
  exact Finset.union_self context.paths

/-- The semiring order is inclusion of finite path collections. -/
instance [Encodable Hom] : IdemSemiring (HomContext Hom) :=
  IdemSemiring.ofSemiring add_self

/-- The canonical order on contexts is exactly inclusion of their paths. -/
@[simp]
theorem le_iff_paths_subset [Encodable Hom] (left right : HomContext Hom) :
    left ≤ right ↔ left.paths ⊆ right.paths := by
  constructor
  · intro below
    have equality : left + right = right := below.add_eq_right
    have pathEquality := congrArg HomContext.paths equality
    exact Finset.union_eq_right.mp pathEquality
  · intro subset
    apply add_eq_right_iff_le.mp
    apply ext
    exact Finset.union_eq_right.mpr subset

end HomContext

end ACUIHE.Solver.Linear
